"""add user table

Revision ID: 0b9a301a0507
Revises: 92d01624181a
Create Date: 2024-09-19 22:28:10.267917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9a301a0507'
down_revision: Union[str, None] = '92d01624181a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('food', sa.String(), nullable=False),
    sa.Column('amount_eaten', sa.Integer(), nullable=False),
    sa.Column('calories', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    # ### end Alembic commands ###
