"""add user table

Revision ID: c6870abf37a1
Revises: 57a3ec0a4ddc
Create Date: 2024-09-19 22:43:37.660434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6870abf37a1'
down_revision: Union[str, None] = '57a3ec0a4ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('per_amount', sa.String(), nullable=False),
    sa.Column('micronutrient', sa.String(), nullable=False),
    sa.Column('mn_amount', sa.DECIMAL(), nullable=False),
    sa.Column('daily_value_percent', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition')
    # ### end Alembic commands ###
