"""add user table

Revision ID: ceeb7080ba70
Revises: c6870abf37a1
Create Date: 2024-09-19 23:00:01.044366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceeb7080ba70'
down_revision: Union[str, None] = 'c6870abf37a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_db',
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('food_group', sa.String(), nullable=False),
    sa.Column('avg_serving_size', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_db'))
    )
    op.create_table('nutrition_info',
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('per_amount', sa.String(), nullable=False),
    sa.Column('micronutrient', sa.String(), nullable=False),
    sa.Column('mn_amount', sa.DECIMAL(), nullable=False),
    sa.Column('daily_value_percent', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_info'))
    )
    op.create_table('user_meals',
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('food', sa.String(), nullable=False),
    sa.Column('amount_eaten', sa.Integer(), nullable=False),
    sa.Column('calories', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_meals'))
    )
    op.drop_table('meals')
    op.drop_table('nutrition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('per_amount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('micronutrient', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mn_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('daily_value_percent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_nutrition')
    )
    op.create_table('meals',
    sa.Column('userID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('food', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount_eaten', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_meals')
    )
    op.drop_table('user_meals')
    op.drop_table('nutrition_info')
    op.drop_table('food_db')
    # ### end Alembic commands ###
